version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: xeno-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - xeno_mongo_data:/data/db

  channel-service:
    build:
      context: ./channel-service
      dockerfile: Dockerfile
    container_name: xeno-channel-service
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "5100:5100"
    environment:
      PORT: 5100
      NODE_ENV: production
      WEBHOOK_SECRET: xeno-demo-secret
      SIMULATION_SPEED: 0.45

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: xeno-backend
    restart: unless-stopped
    depends_on:
      - mongodb
      - channel-service
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/xeno
      CLIENT_URLS: http://localhost:5173
      PUBLIC_API_URL: http://backend:5000/api
      CHANNEL_SERVICE_URL: http://channel-service:5100/api/simulations
      WEBHOOK_SECRET: xeno-demo-secret
      SIMULATION_SPEED: 0.45
      JWT_SECRET: please-change-me
      JWT_EXPIRES_IN: 1d

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xeno-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  xeno_mongo_data:
